@startuml Broker Selection
start
if (Do you want to send file through message broker?) then (Yes)
    :**Choose gRPC**;
    stop
else (No)
    if (What kind of communication between your services?) then (Request/Reply)
			:**Choose NATS**;
			stop
    else (Distributing)
        if(You want to process message after received (Log Analysis)?) then (Yes)
            :**Choose NATS JetStream with Logstash**;
            stop
        else (No)
            if(Does your system only run on premise or you not okay for message to send over internet?) then (Yes)
                :**Choose NATS JetStream**;
                stop
            else (No)
                if (Do you want to maintain the message broker service?) then (Yes)
                    :**Choose NATS JetStream**;
                    stop
                else (No)
                    :**Choose AWS SQS**;
                    stop
            endif
        endif
    endif
endif
@enduml